protocols_involved('UDP', 'FTP', 'Malware').
protocols_involved('TCP', 'HTTP', 'Malware').
protocols_involved('UDP', 'HTTP', 'Intrusion').
protocols_involved('UDP', 'FTP', 'DDoS').
protocols_involved('TCP', 'HTTP', 'DDoS').
protocols_involved('TCP', 'DNS', 'Intrusion').
protocols_involved('TCP', 'FTP', 'Intrusion').
protocols_involved('ICMP', 'HTTP', 'Malware').
protocols_involved('UDP', 'HTTP', 'Malware').
protocols_involved('ICMP', 'HTTP', 'DDoS').
protocols_involved('UDP', 'DNS', 'Intrusion').
protocols_involved('ICMP', 'DNS', 'Intrusion').
protocols_involved('TCP', 'DNS', 'Malware').
protocols_involved('UDP', 'HTTP', 'DDoS').
protocols_involved('ICMP', 'FTP', 'Intrusion').
protocols_involved('TCP', 'FTP', 'Malware').
protocols_involved('TCP', 'DNS', 'DDoS').
protocols_involved('UDP', 'FTP', 'Intrusion').
protocols_involved('TCP', 'HTTP', 'Intrusion').
protocols_involved('TCP', 'FTP', 'DDoS').
protocols_involved('UDP', 'DNS', 'Malware').
protocols_involved('ICMP', 'DNS', 'Malware').
protocols_involved('UDP', 'DNS', 'DDoS').
protocols_involved('ICMP', 'FTP', 'Malware').
protocols_involved('ICMP', 'DNS', 'DDoS').
protocols_involved('ICMP', 'HTTP', 'Intrusion').
protocols_involved('ICMP', 'FTP', 'DDoS').
